"""add_partial_failed_status_and_parse_error

Revision ID: a43ba04bf415
Revises: 52ad6a85a96f
Create Date: 2026-07-07 12:55:09.093791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43ba04bf415'
down_revision: Union[str, None] = '52ad6a85a96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_favorite', 'favorites', type_='unique')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.drop_index('ix_push_subscriptions_user_id', table_name='push_subscriptions')
    op.alter_column('scrape_results', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # Add parse_error column to track per-listing validation/parse errors
    op.add_column('scrape_results', sa.Column('parse_error', sa.Text(), nullable=True))
    op.drop_index('ix_scrape_results_created_at', table_name='scrape_results')
    op.drop_index('ix_scrape_results_task_id', table_name='scrape_results')
    op.drop_index('scrape_results_created_at_idx', table_name='scrape_results')
    op.drop_index('scrape_results_task_id_url_idx', table_name='scrape_results', postgresql_where='(url IS NOT NULL)')
    op.alter_column('scrape_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_scrape_tasks_status', table_name='scrape_tasks')
    op.drop_constraint('unique_task_daily_usage', 'token_usage', type_='unique')
    op.create_index(op.f('ix_token_usage_id'), 'token_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_id'), table_name='token_usage')
    op.create_unique_constraint('unique_task_daily_usage', 'token_usage', ['task_id', 'date'])
    op.create_index('ix_scrape_tasks_status', 'scrape_tasks', ['status'], unique=False)
    op.alter_column('scrape_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('scrape_results_task_id_url_idx', 'scrape_results', ['task_id', 'url'], unique=True, postgresql_where='(url IS NOT NULL)')
    op.create_index('scrape_results_created_at_idx', 'scrape_results', ['created_at'], unique=False)
    op.create_index('ix_scrape_results_task_id', 'scrape_results', ['task_id'], unique=False)
    op.create_index('ix_scrape_results_created_at', 'scrape_results', ['created_at'], unique=False)
    # Drop parse_error column on downgrade
    op.drop_column('scrape_results', 'parse_error')
    op.alter_column('scrape_results', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_push_subscriptions_user_id', 'push_subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_unique_constraint('unique_user_favorite', 'favorites', ['user_id', 'result_id'])
    # ### end Alembic commands ###
