apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kleinanzeigen-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kleinanzeigen-kv-dev"     # Change per environment
    objects: |
      array:
        - |
          objectName: DatabaseConnectionString
          objectType: secret
        - |
          objectName: RedisConnectionString
          objectType: secret
        - |
          objectName: SecretKey
          objectType: secret
        - |
          objectName: GoogleClientId
          objectType: secret
        - |
          objectName: GoogleClientSecret
          objectType: secret
    tenantId: "f196df42-b27f-416b-b16f-d6f83a94cd0f"          # Replace with your Azure AD tenant ID

  # Syncs Key Vault secrets into a Kubernetes Secret named kleinanzeigen-secrets
  secretObjects:
    - secretName: kleinanzeigen-secrets
      type: Opaque
      data:
        - objectName: DatabaseConnectionString
          key: DATABASE_URL
        - objectName: RedisConnectionString
          key: REDIS_URL
        - objectName: SecretKey
          key: SECRET_KEY
        - objectName: GoogleClientId
          key: GOOGLE_CLIENT_ID
        - objectName: GoogleClientSecret
          key: GOOGLE_CLIENT_SECRET
